travis:
  secure:
    BINSTAR_TOKEN: JxaY9uT24hsM1lOv+dfJnUu35EM6fRwIslCAu2rt5QoU/3HycH1XaNEdxIXHNuXpWEWlvwneyFgQCYY2VabZU+tLlUlHNv3aIP14/SorWjnux9WXxye/yQXDIaLBelEe2+pLBNDGY/LaeWx75vv6bd7F3rZ1z+pTOMXrU/2Vq8L1D7EKCKVHlaj9cP6U2eWgczhRGwRigNLpXBoYBg1mXVrrpcyB9H7PL7NuHEYhrhZBnoXlgvUTXcn25/jWR2MBI/MaINfgS/dn15kj5sm/PMj0tU28ChxNCeJl+FRBN4HNVwcoYnecHxxNJIHf0K/nAyfi7FMZOzaLkfPawep0skLnhTQ3vel8yU7k2f9M3PIY7nD3iTavFqI1aqk+AdXybp3Y4ephX7t7iGWkI6Ice5CLjHUJXrJ9H2wevEO11CHPqnpNuQQ89YEx9PoOlvTagxvaJLieBFgIiZ4ZZZwW2C6GZBlxMZKYlsHRVN/gWATHs4WN/94Ei2a+jfZ9jp5RYlx+My8vGav3AnM5jIXY4dXTIoJN/vMQ8W5jGiGrYu9pLdz9oraEfZXKL+IT0b3qlibcjPWglhyCu561z+ljbpNEj/patsJ8+EUX5SQLfEBwX6qrlD+ysXIVI4DdxljwF/qpMw23EzVkb9z8yJmQG9pssuD3gLkeIDrbacYpR70=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
